spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/example?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 9092
  servlet:
    context-path: /summer